import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Header } from "@/_components/Header";
import styles from "../page.module.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ArchiveLayout({
  archive,
  latest
}: Readonly<{
  archive: React.ReactNode;
  latest: React.ReactNode;
}>) {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <h1>News Archive</h1>
        <br/>
        <section>
        {archive}
        </section>
        <br/>
        <br/>
        <section>
        {latest}
        </section>
        <br/>
        <Link href={"/"}>{"<- back"}</Link>
      </main>
    </div>
  
  );
}
